provider "aws" {
  region = "us-east-1"
}

resource "aws_db_instance" "rds" {
  identifier = "book-rds"

  engine         = "mysql"
  engine_version = "8.0"

  instance_class = "db.t3.micro"

  allocated_storage = 20

  db_name  = "bookdb"
  username = "admin"
  password = "Admin1234!"

  # ✅ CRITICAL FIX
  backup_retention_period = 1
  multi_az               = false

  publicly_accessible = true
  skip_final_snapshot = true

  vpc_security_group_ids = ["sg-0278aec1b35fc3645"]

  tags = {
    Name = "book-rds"
  }
}

output "rds_endpoint" {
  value = aws_db_instance.rds.endpoint
}
