provider "aws" {
  region = "us-east-1"
}

resource "aws_db_instance" "rds" {
  identifier = "book-rds"

  engine         = "mysql"
  engine_version = "8.0"

  instance_class = "db.t3.micro"

  allocated_storage = 20
  storage_type      = "gp2"

  db_name  = "bookdb"
  username = "admin"
  password = "Admin1234!"

  port = 3306

  # ✅ FIX FREE TIER (CRITICAL)
  backup_retention_period = 1
  multi_az               = false

  # ✅ ACCESS
  publicly_accessible = true

  # ✅ REQUIRED
  skip_final_snapshot = true
  apply_immediately   = true

  # ✅ USE YOUR SG (OK)
  vpc_security_group_ids = ["sg-0278aec1b35fc3645"]

  tags = {
    Name = "book-rds"
  }
}

# ✅ OUTPUTS
output "rds_endpoint" {
  value = aws_db_instance.rds.endpoint
}

output "rds_port" {
  value = aws_db_instance.rds.port
}
