name: Terraform VPC Deploy

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: "Choose action"
        required: true
        type: choice
        default: apply
        options:
          - apply
          - plan
          - destroy
      destroy_confirmation:
        description: "Type DESTROY to confirm"
        required: false
        type: string

permissions:
  contents: read

jobs:
  vpc-terraform:
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: terraform-ecs-fargate-fullstack-app/vpc-network

      # ✅ FIX SIMPLE ET STABLE
      AWS_REGION: us-east-1
      TF_STATE_BUCKET: amen-terraform
      TF_LOCK_TABLE: terraform-lock-table

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Debug info
        run: |
          echo "AWS REGION: $AWS_REGION"
          echo "WORK DIR: $TF_WORKING_DIR"
          echo "BUCKET: $TF_STATE_BUCKET"
          echo "LOCK TABLE: $TF_LOCK_TABLE"

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init \
            -backend-config="bucket=$TF_STATE_BUCKET" \
            -backend-config="key=vpc-network/terraform.tfstate" \
            -backend-config="region=$AWS_REGION" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=$TF_LOCK_TABLE"

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        if: inputs.terraform_action == 'plan' || inputs.terraform_action == 'apply'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan

      - name: Confirm Destroy
        if: inputs.terraform_action == 'destroy'
        run: |
          if [ "${{ inputs.destroy_confirmation }}" != "DESTROY" ]; then
            echo "Destroy not confirmed"
            exit 1
          fi

      - name: Terraform Apply
        if: inputs.terraform_action == 'apply'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: inputs.terraform_action == 'destroy' && inputs.destroy_confirmation == 'DESTROY'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve
